name: deploy react

on:
    push:
        branches:
            - main
            - develop
        paths:
            - client/**

jobs:
    build:
        env:
            CI: false
        name: React build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "./client"
        steps:
            - name: checkout code
              uses: actions/checkout@v3.3.0

            - name: cache dependecy
              uses: actions/cache@v3.2.3
              with:
                  path: node_modules
                  key: ${{runner.os}}-build-${{hashFiles('**/package-lock.json')}}
                  restore-key: |
                      ${{runner.os}}-build-
                      ${{runner.os}}-

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: configure aws s3
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: Deploy
              env:
                  BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME}}
              run: aws s3 sync ./build s3://$BUCKET_NAME
